#ifndef ESTADISTICASGIMNASIOCORE_GLOBAL_H
#define ESTADISTICASGIMNASIOCORE_GLOBAL_H

#include <QtCore/qglobal.h>

#if defined(ESTADISTICASGIMNASIOCORE_LIBRARY)
#  define ESTADISTICASGIMNASIOCORE_EXPORT Q_DECL_EXPORT
#else
#  define ESTADISTICASGIMNASIOCORE_EXPORT Q_DECL_IMPORT
#endif

#endif // ESTADISTICASGIMNASIOCORE_GLOBAL_H
